apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
    - job_name: 'flask-app'
      static_configs:
        - targets: ['flask-service:5000']
